pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: CIEnabled
  type: boolean
  displayName: CI Enabled
  default: false
  values:
  - true
  - false
- name: CIVersion
  displayName: CI Version 
  type: string
  default: v1

variables:
  civersion: ${{ parameters.CIVersion }}

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true
- task: AzureCLI@2
  displayName: "CI for Kaiyo LandingPage"
  inputs:
    azureSubscription: 'Kaiyo(9e4608a6-6d91-473e-9d62-f76f36d4ed02)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'ci.sh'
    arguments: 'ci $(civersion)'
  condition: eq('${{ parameters.CIEnabled }}', true)

- task: AzureCLI@2
  displayName: "CD for Kaiyo LandingPage"
  inputs:
    azureSubscription: 'Kaiyo(9e4608a6-6d91-473e-9d62-f76f36d4ed02)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'ci.sh'
    arguments: 'cd landing-page deploy_values.yaml $(civersion)'
