replicaCount: 1

serviceAccount:
  name: "landing-page"

image:
  repository: kaiyocloud.azurecr.io/landing-page-kaiyo-service

liveness:
  endpoint: /health
  initialDelaySeconds: 10
  periodSeconds: 5

readiness:
  endpoint: /health
  initialDelaySeconds: 10
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 1500m
    memory: 900Mi
  requests:
    cpu: 100m
    memory: 100Mi